class Presets:

    def __init__(self, grid):
        self.grid = grid
        self.columns = grid.columns
        self.boxes = grid.boxes
        self.options = {
            "Glider": self.glider,
            "Glider Gun": self.glider_gun,
            "Pulsar": self.pulsar,
        }

    def glider(self):
        self.grid.reset_grid()
        self.boxes[0, self.columns - 3].switch_state()
        self.boxes[1, self.columns - 4].switch_state()
        self.boxes[2, self.columns - 4].switch_state()
        self.boxes[2, self.columns - 3].switch_state()
        self.boxes[2, self.columns - 2].switch_state()

    def glider_gun(self):
        self.grid.reset_grid()
        self.boxes[10, 1].switch_state()
        self.boxes[11, 1].switch_state()
        self.boxes[10, 2].switch_state()
        self.boxes[11, 2].switch_state()
        self.boxes[11, 9].switch_state()
        self.boxes[12, 9].switch_state()
        self.boxes[10, 10].switch_state()
        self.boxes[12, 10].switch_state()
        self.boxes[10, 11].switch_state()
        self.boxes[11, 11].switch_state()
        self.boxes[12, 17].switch_state()
        self.boxes[13, 17].switch_state()
        self.boxes[14, 17].switch_state()
        self.boxes[12, 18].switch_state()
        self.boxes[13, 19].switch_state()
        self.boxes[9, 23].switch_state()
        self.boxes[10, 23].switch_state()
        self.boxes[8, 24].switch_state()
        self.boxes[10, 24].switch_state()
        self.boxes[8, 25].switch_state()
        self.boxes[9, 25].switch_state()
        self.boxes[20, 25].switch_state()
        self.boxes[21, 25].switch_state()
        self.boxes[20, 26].switch_state()
        self.boxes[22, 26].switch_state()
        self.boxes[20, 27].switch_state()
        self.boxes[8, 35].switch_state()
        self.boxes[9, 35].switch_state()
        self.boxes[8, 36].switch_state()
        self.boxes[9, 36].switch_state()
        self.boxes[15, 36].switch_state()
        self.boxes[16, 36].switch_state()
        self.boxes[17, 36].switch_state()
        self.boxes[15, 37].switch_state()
        self.boxes[16, 38].switch_state()

    def pulsar(self):
        self.grid.reset_grid()
        self.boxes[11, 9].switch_state()
        self.boxes[12, 9].switch_state()
        self.boxes[13, 9].switch_state()
        self.boxes[17, 9].switch_state()
        self.boxes[18, 9].switch_state()
        self.boxes[19, 9].switch_state()
        self.boxes[9, 11].switch_state()
        self.boxes[14, 11].switch_state()
        self.boxes[16, 11].switch_state()
        self.boxes[21, 11].switch_state()
        self.boxes[9, 12].switch_state()
        self.boxes[14, 12].switch_state()
        self.boxes[16, 12].switch_state()
        self.boxes[21, 12].switch_state()
        self.boxes[9, 13].switch_state()
        self.boxes[14, 13].switch_state()
        self.boxes[16, 13].switch_state()
        self.boxes[21, 13].switch_state()
        self.boxes[11, 14].switch_state()
        self.boxes[12, 14].switch_state()
        self.boxes[13, 14].switch_state()
        self.boxes[17, 14].switch_state()
        self.boxes[18, 14].switch_state()
        self.boxes[19, 14].switch_state()
        self.boxes[11, 16].switch_state()
        self.boxes[12, 16].switch_state()
        self.boxes[13, 16].switch_state()
        self.boxes[17, 16].switch_state()
        self.boxes[18, 16].switch_state()
        self.boxes[19, 16].switch_state()
        self.boxes[9, 17].switch_state()
        self.boxes[14, 17].switch_state()
        self.boxes[16, 17].switch_state()
        self.boxes[21, 17].switch_state()
        self.boxes[9, 18].switch_state()
        self.boxes[14, 18].switch_state()
        self.boxes[16, 18].switch_state()
        self.boxes[21, 18].switch_state()
        self.boxes[9, 19].switch_state()
        self.boxes[14, 19].switch_state()
        self.boxes[16, 19].switch_state()
        self.boxes[21, 19].switch_state()
        self.boxes[11, 21].switch_state()
        self.boxes[12, 21].switch_state()
        self.boxes[13, 21].switch_state()
        self.boxes[17, 21].switch_state()
        self.boxes[18, 21].switch_state()
        self.boxes[19, 21].switch_state()